name: sparrow-home
services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    env_file: ./server-data/.env
    environment:
      POSTGRES_DB: ${dbName}
      POSTGRES_USER: ${dbUserName}
      POSTGRES_PASSWORD: ${dbPassword}
      TZ: ${timeZone}
    volumes:
      - ./server-data/postgres_data:/var/lib/postgresql
    networks: [sparrow]

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    environment:
      TZ: ${timeZone}
    networks: [sparrow]

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      TZ: ${timeZone}
      ZIGBEE_SERIAL_PORT: ${zigbeeSerialPort}
      ZIGBEE_ADAPTER: ${zigbeeAdapter}

    volumes:
      - ./server-data/zigbee2mqtt/data:/app/data
      - ./home-server/zigbee2mqtt/scripts:/app/scripts:ro
      - /run/udev:/run/udev:ro

    devices:
      - ${zigbeeSerialPort}:${zigbeeSerialPort}

    command: [ "/bin/sh", "/app/scripts/generate-config.sh" ]
    networks: [sparrow]

  backend:
    image: ghcr.io/sparrow-codes/sparrow-backend:current
    restart: unless-stopped
    depends_on: [postgres, mosquitto, zigbee2mqtt]
    env_file: ./server-data/.env
    environment:
      mode: ${mode}
      dbHost: postgres
      dbPort: 5432
      dbName: ${dbName}
      dbUserName: ${dbUserName}
      dbPassword: ${dbPassword}
      jwtSecret: ${jwtSecret}
      jwtExpiry: ${jwtExpiry}
      mqttUrl: mqtt://mosquitto
      pushPublicKey: ${pushPublicKey}
      pushPrivateKey: ${pushPrivateKey}
      pushAdminEmail: ${pushAdminEmail}
      TZ: ${timeZone}
    volumes:
      - ./server-data/backend/data:/app/data
    networks: [sparrow]

  frontend:
    image: ghcr.io/sparrow-codes/sparrow-frontend:current
    restart: unless-stopped
    depends_on: [backend]
    user: "0:0"
    environment:
      TAILSCALE_DOMAIN: ${tailscaleDomain}
      TZ: ${timeZone}
      pushPublicKey: ${pushPublicKey}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./home-server/frontend/scripts:/scripts:ro
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    networks: [sparrow]
    command:
      - /bin/sh
      - /scripts/generate-config.sh

networks:
  sparrow:
    driver: bridge
