services:
  postgres:
    image: postgres:latest
    container_name: sparrow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sparrow_home
      POSTGRES_USER: sparrow
      POSTGRES_PASSWORD: sparrow
    ports:
      - "5432:5432"
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: sparrow-mqtt
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: sparrow-zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mqtt
    ports:
      - "8080:8080"
    environment:
      TZ: Europe/Warsaw
