services:
  postgres:
    image: postgres:latest
    container_name: sparrow-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${dbName}
      POSTGRES_USER: ${dbUserName}
      POSTGRES_PASSWORD: ${dbPassword}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: sparrow-mqtt
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: sparrow-zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mosquitto
    env_file: .env
    environment:
      TZ: ${zigbeeTimeZone}
      ZIGBEE2MQTT_MQTT_SERVER: mqtt://mosquitto
      ZIGBEE2MQTT_SERIAL_ADAPTER: ${zigbeeSerialAdapter}
      ZIGBEE2MQTT_FRONTEND: "false"
      ZIGBEE2MQTT_PERMIT_JOIN: "false"
      ZIGBEE2MQTT_ADVANCED_NETWORK_KEY: GENERATE
    volumes:
      - ./zigbee2mqtt/data:/app/data
#    devices:
#      - "${zigbeeSerialPort}:${zigbeeSerialPort}"

  nodejs:
    depends_on:
      - postgres
      - mosquitto
      - zigbee2mqtt
    build:
      context: ../
      dockerfile: ./scripts/backend/Dockerfile
    container_name: sparrow-home-backend
    restart: unless-stopped
    env_file: .env
    environment:
      mode: ${mode}
      dbHost: postgres
      dbPort: 5432
      dbName: ${dbName}
      dbUserName: ${dbUserName}
      dbPassword: ${dbPassword}
      jwtSecret: ${jwtSecret}
      jwtExpiry: ${jwtExpiry}
      mqttUrl: mqtt://mosquitto
      pushPublicKey: ${pushPublicKey}
      pushPrivateKey: ${pushPrivateKey}
      pushAdminEmail: ${pushAdminEmail}
    volumes:
      - ./data:/app/data
  frontend:
    build:
      context: ../
      dockerfile: ./scripts/frontend/Dockerfile
    container_name: sparrow-home-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./frontend/config.json:/usr/share/nginx/html/config.json:ro
